Fix `make check` by pre-installing postgres_fdw. (#284)
Tests performed by `make check` use several extensions, including contrib/postgres_fdw, but this extension isn't mentioned in Makefile, causing errors like:

ERROR:  extension "postgres_fdw" is not available
ERROR:  foreign-data wrapper "postgres_fdw" does not exist

and so on. This patch fixes this by adding contrib/postgres_fdw to a relevant variable in the makefile.

Reviewed by David Steele (@dwsteele)